// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/admin/options": {
            "put": {
                "description": "更新配置项信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "配置项"
                ],
                "summary": "更新配置项",
                "parameters": [
                    {
                        "description": "配置项",
                        "name": "option",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"message\":\"成功\",\"result\":{\"key\":\"WEBSITE_NAME\",\"value\":{\"data\":\"New Silk Road\"},\"label\":\"网站名称\",\"isPublic\":true,\"CreatedAt\":\"2023-05-21T15:29:42.6390127+08:00\",\"UpdatedAt\":\"2023-05-23T10:31:12.1234567+08:00\"}}",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "400": {
                        "description": "{\"success\":false,\"message\":\"请求无效或参数错误\",\"result\":null}",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "404": {
                        "description": "{\"success\":false,\"message\":\"未找到配置项\",\"result\":null}",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "429": {
                        "description": "{\"success\":false,\"message\":\"请求过于频繁，请稍后再试！\",\"result\":null}",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/v1/public-options": {
            "get": {
                "description": "获取公开的配置项信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "配置项"
                ],
                "summary": "获取公开的配置项",
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"message\":\"成功\",\"result\":[{\"key\":\"WEBSITE_NAME\",\"value\":{\"data\":\"Silk Road\"},\"label\":\"网站名称\",\"isPublic\":true,\"CreatedAt\":\"2023-05-21T15:29:42.6390127+08:00\",\"UpdatedAt\":\"2023-05-21T15:29:42.6390127+08:00\"}, {...}]}",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "429": {
                        "description": "{\"success\":false,\"message\":\"请求过于频繁，请稍后再试！\",\"result\":null}",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        },
        "/v1/system/info": {
            "get": {
                "description": "获取系统应用程序名称和版本号",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统信息"
                ],
                "summary": "获取系统信息",
                "responses": {
                    "200": {
                        "description": "{\"success\":true,\"message\":\"Success\",\"result\":{\"appName\":\"GoApp\",\"appVersion\":\"1.0.0\"}}",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    },
                    "429": {
                        "description": "{\"success\":false,\"message\":\"请求过于频繁，请稍后再试！\",result:null}",
                        "schema": {
                            "$ref": "#/definitions/utils.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "utils.Response": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "result": {},
                "success": {
                    "type": "boolean"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{"http"},
	Title:            "Silk Road",
	Description:      "The API doc of Silk Road.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
