basePath: /api
definitions:
  utils.Response:
    properties:
      message:
        type: string
      result: {}
      success:
        type: boolean
    type: object
info:
  contact: {}
  description: The API doc of Silk Road.
  title: Silk Road
  version: 1.0.0
paths:
  /v1/admin/login:
    post:
      consumes:
      - application/json
      description: 管理员使用用户名和密码进行登录
      parameters:
      - description: 用户名
        in: body
        name: username
        required: true
        schema:
          type: string
      - description: 密码
        in: body
        name: password
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"message":"登录成功！","result":null}'
          schema:
            $ref: '#/definitions/utils.Response'
        "400":
          description: '{"success":false,"message":"用户名或密码错误！","result":null}'
          schema:
            $ref: '#/definitions/utils.Response'
      summary: 管理员登录
      tags:
      - 管理员
  /v1/admin/settings/{key}:
    put:
      consumes:
      - application/json
      description: 更新配置项信息
      parameters:
      - description: 配置项键
        in: path
        name: key
        required: true
        type: string
      - description: 配置项新值
        in: body
        name: value
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"message":"更新成功","result":{"key":"WEBSITE_TITLE","value":{"data":"New
            Silk Road"},"label":"网站名称","isPublic":true,"CreatedAt":"2023-05-21T15:29:42.6390127+08:00","UpdatedAt":"2023-05-23T10:31:12.1234567+08:00"}}'
          schema:
            $ref: '#/definitions/utils.Response'
        "400":
          description: '{"success":false,"message":"请求无效或参数错误","result":null}'
          schema:
            $ref: '#/definitions/utils.Response'
        "404":
          description: '{"success":false,"message":"未找到配置项","result":null}'
          schema:
            $ref: '#/definitions/utils.Response'
        "429":
          description: '{"success":false,"message":"请求过于频繁，请稍后再试！","result":null}'
          schema:
            $ref: '#/definitions/utils.Response'
      summary: 更新配置项
      tags:
      - 配置项
  /v1/public-settings:
    get:
      consumes:
      - application/json
      description: 获取公开的配置项信息
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"message":"成功","result":{"UPLOAD_FILE_SIZE_LIMIT":10,
            ...}}'
          schema:
            $ref: '#/definitions/utils.Response'
        "429":
          description: '{"success":false,"message":"请求过于频繁，请稍后再试！","result":null}'
          schema:
            $ref: '#/definitions/utils.Response'
      summary: 获取公开的配置项
      tags:
      - 配置项
  /v1/settings:
    get:
      consumes:
      - application/json
      description: 获取所有配置项信息
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"message":"成功","result":[{"key":"UPLOAD_FILE_SIZE_LIMIT","value":{"data":10},"label":"上传大小限制","isPublic":true,"createdAt":"2023-05-22T15:10:40.7958637+08:00","updatedAt":"2023-05-22T15:10:40.7958637+08:00"},
            {...}]}'
          schema:
            $ref: '#/definitions/utils.Response'
        "429":
          description: '{"success":false,"message":"请求过于频繁，请稍后再试！","result":null}'
          schema:
            $ref: '#/definitions/utils.Response'
      summary: 获取所有配置项
      tags:
      - 配置项
  /v1/system/info:
    get:
      consumes:
      - application/json
      description: 获取系统应用程序名称和版本号
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"message":"Success","result":{"appName":"GoApp","appVersion":"1.0.0"}}'
          schema:
            $ref: '#/definitions/utils.Response'
        "429":
          description: '{"success":false,"message":"请求过于频繁，请稍后再试！",result:null}'
          schema:
            $ref: '#/definitions/utils.Response'
      summary: 获取系统信息
      tags:
      - 系统信息
schemes:
- http
swagger: "2.0"
